version: '3.8'
services:
  api:
    build: api
    restart: on-failure
    ports:
      - 8000:80
    volumes:
      - ~/.cache/huggingface:/app/.cache/huggingface
      - ./api/outputs:/app/outputs
      - ./api/api:/app/api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      LOG_LEVEL: DEBUG
  bot:
    build: bot
    restart: on-failure
    depends_on:
      - api
    volumes:
      - ./bot/outputs:/app/outputs
    env_file: bot/.env
    environment:
      API_URL: http://api:80
